[package]
name = "rbtl"
version = "0.1.0"
edition = "2024"
rust-version = "1.90"

[workspace]
members = [
    "rbtl-core",
    "rbtl-rudp",
    "rbtl-tcp"
]

[dependencies]
rbtl-rudp = { path = "./rbtl-rudp" }
rbtl-tcp = { path = "./rbtl-tcp" }
rbtl-core = { path = "./rbtl-core" }

log = "0.4"
paste = "^1.0"
serde = { version = "^1.0", optional = true }

[features]
default = ["default-export"]
default-export = []

